language : c
compiler : gcc
os : linux
before_install:
    - pip install --user cpp-coveralls
script : 
    - make -j8
    - ./build/test test.at > log && diff log stdlog
after_success:
    - coveralls --exclude=test.c --gcov-options='\-lp'
